spring:
  application:
    name: discovery-service
eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    enabled: true
    fetch-registry: true
    register-with-eureka: false
server:
  port: 8761
  spring:
    boot:
      admin:
        client:
          url: http://localhost:8099